[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.92.0"
  HUGO_ENV = "production"
  NODE_VERSION = "14"

# 指定构建分支
[context.main]
  command = "hugo --gc --minify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200